[project]
name = "ai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.20",
    "openai>=1.66.5",
    "pypdf",
    "python-docx>=1.1.2",
    "streamlit>=1.43.2",
]
